resource_maps/urls.py
from django.urls import path
from . import views

app_name = 'resource_maps'

urlpatterns = [
    path('map/', views.map_view, name='map_voting'),
    path('map-voting/', views.map_view, name='map_voting'),
    path('map-voting/<int:waypoint_id>/vote/<str:vote_option>/', views.vote_waypoint, name='vote_waypoint'),
    path('map-voting/<int:waypoint_id>/info/', views.waypoint_info, name='waypoint_info'),
]

weather/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path('forecast/', views.forecast, name='forecast'),
]

resource_maps/models.py
from django.db import models
from django.db.models import Q, Count
from django.contrib.auth.models import User
from django.utils import timezone


class ResourceCategory(models.Model):
    type = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.type

class Waypoint(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    latitude = models.FloatField()
    longitude = models.FloatField()
    category = models.ForeignKey(ResourceCategory, on_delete=models.SET_NULL, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    votes_yes = models.IntegerField(default=0)
    votes_no = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def tally_votes(self):
        # Returns a dictionary with the total present and absent votes
        votes = self.votes.aggregate(
            present_count=Count('id', filter=Q(vote=True)),
            absent_count=Count('id', filter=Q(vote=False))
        )
        return votes

    def vote_score(self):
        # A simple vote score might just be present votes minus absent votes
        return self.votes_yes - self.votes_no


    def vote_percentage(self):
        # Calculates the percentage of yes votes
        total_votes = self.votes_yes + self.votes_no
        if total_votes == 0:
            return 0  # Avoid division by zero
        return (self.votes_yes / total_votes) * 100

    def __str__(self):
        return f"{self.name} at {self.latitude}, {self.longitude}"


class Vote(models.Model):
    waypoint = models.ForeignKey(Waypoint, related_name='votes', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    vote_date = models.DateTimeField(auto_now_add=True)
    vote = models.BooleanField()  # True for resource present, False for resource absent

    class Meta:
        unique_together = ('waypoint', 'user', 'vote_date')  # Ensures unique votes per user per day

    def __str__(self):
        return f"Vote by {self.user} for {self.waypoint.name} as {'present' if self.vote else 'absent'}"

resource_maps/views.py
import json
from .models import Waypoint
from django.db.models import F
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.http import JsonResponse
from django.core.serializers import serialize
from django.views.decorators.http import require_http_methods
import logging

logger = logging.getLogger(__name__)


def map_view(request):
    waypoints = Waypoint.objects.filter(is_active=True)
    waypoints_json = serialize('json', waypoints)
    vote_scores = {waypoint.id: waypoint.vote_score() for waypoint in waypoints}
    vote_percentages = {waypoint.id: waypoint.vote_percentage() for waypoint in waypoints}

    context = {
        'waypoints_json': waypoints_json,
        'waypoints': waypoints,
        'vote_scores': vote_scores,
        'vote_percentages': vote_percentages,
    }

    return render(request, 'resource_maps/map_voting.html', context)


def waypoint_info(request, waypoint_id):
    waypoint = get_object_or_404(Waypoint, pk=waypoint_id)
    vote_score = waypoint.vote_score()
    vote_percentage = waypoint.vote_percentage()

    context = {
        'waypoint': waypoint,
        'vote_score': vote_score,
        'vote_percentage': vote_percentage,
    }

    return render(request, 'resource_maps/waypoint_info.html', context)

@require_http_methods(["POST"])
def vote_waypoint(request, waypoint_id, vote_option):
    logger.debug(f"Voting {vote_option} on waypoint {waypoint_id}")
    waypoint = get_object_or_404(Waypoint, pk=waypoint_id)
    # Updating votes to ensure thread safety
    if vote_option == 'yes':
        Waypoint.objects.filter(pk=waypoint_id).update(votes_yes=F('votes_yes') + 1)
    elif vote_option == 'no':
        Waypoint.objects.filter(pk=waypoint_id).update(votes_no=F('votes_no') + 1)
    waypoint.refresh_from_db()  # Refresh the instance to get updated values from the database

    return JsonResponse({
        'waypoint_id': waypoint.id,
        'vote_score': waypoint.vote_score(),
        'vote_percentage': waypoint.vote_percentage()
    })

resource_maps/templates/resource_maps/base.html
<!DOCTYPE html>
{% load static %}
{% load custom_filters %}
<html lang="en">
  <head>

      <meta charset="utf-8" />
      <meta name="csrf-token" content="{{ csrf_token }}" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>

      {% block title %}
        Resource Map
      {% endblock %}
      </title>
      <!-- Inside the <head> section -->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" />
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'imgs/ico.webp' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Resource Map</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div>
    </nav>

    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC7mz3cFgW2AiTqfBAGQdp7NooU6eq0Ci4&callback=initMap"></script>


    <script>
        var currentWaypoint = null;

        function initMap() {
            var mapOptions = {
                center: new google.maps.LatLng(18.2244, -66.0457),
                zoom: 14
            };

            const map = new google.maps.Map(document.getElementById('map'), mapOptions);

            waypoints.forEach(function (waypoint) {
                var markerPosition = new google.maps.LatLng(waypoint.latitude, waypoint.longitude);
                var marker = new google.maps.Marker({
                    position: markerPosition,
                    map: map,
                    title: waypoint.fields.name // assuming you have a name field
                });
                // Add click event to each marker to open the voting modal
                marker.addListener('click', function() {
                    $('#waypointModal-' + waypoint.pk).modal('show');
                });
                });$(document).ready(function() {
                    $("#waypointModal-{{ waypoint.pk }}").modal('show');
                });
        } // The google.maps.event.addDomListener line can be removed since it's redundant with the async defer callback
    </script>
    {% block content %}

    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://unpkg.com/htmx.org@1.9.11/dist/htmx.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
      if ('serviceWorker' in navigator) {
        window.addEventListener('load', function () {
          navigator.serviceWorker
            .register('/serviceworker.js', { scope: '/' })
            .then(function (registration) {
              console.log('ServiceWorker registration successful with scope: ', registration.scope)
            })
            .catch(function (err) {
              console.log('ServiceWorker registration failed: ', err)
            })
        })
      }
    </script>
    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
            var csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
            event.detail.headers['X-CSRFToken'] = csrfToken;
        });
</script>

  </body>
</html>

resource_maps/templates/resource_maps/map_voting.html
{% extends "resource_maps/base.html" %}
{% load static %}
{% load custom_filters %}
{% block content %}
<!-- Map container -->
<div id="map" style="height: 600px;"></div>
    <script>
    // Preparing waypoint data from Django context to JavaScript
    var waypoints = JSON.parse('{{ waypoints_json|escapejs }}');
    var voteScores = JSON.parse('{{ vote_scores_json|escapejs }}');
        function updateModalContent(swapInfo) {
            var response = JSON.parse(swapInfo.detail.xhr.responseText);
            // Now update the modal content with the new data
            document.querySelector('#voteScore-' + response.waypoint_id).textContent = "Vote Score: " + response.vote_score;
            document.querySelector('#votePercentage-' + response.waypoint_id).textContent = "Vote Percentage: " + response.vote_percentage + "%";
    }

    // Function to update and show the modal for a waypoint
    function updateAndShowModal(waypointItem) {
        var waypoint = waypointItem.fields; // Access the 'fields' object for each waypoint
        // Set the content of the modal
        var modalID = '#waypointModal-' + waypointItem.pk;
        $(modalID + ' .modal-title').text(waypoint.name);
        $(modalID + ' .modal-body').html(waypoint.description + '<br>Vote Score: ' +
            '<span id="voteScore-' + waypointItem.pk + '">' + (waypoint.votes_yes - waypoint.votes_no) + '</span><br>Vote Percentage: ' +
            '<span id="votePercentage-' + waypointItem.pk + '">' + calculateVotePercentage(waypoint.votes_yes, waypoint.votes_no) + '</span>');

        // Show the modal
        $(modalID).modal('show');
    }
    // Function to handle updating the modal content after a vote


    // Utility function to calculate vote percentage
    function calculateVotePercentage(votesYes, votesNo) {
        var totalVotes = votesYes + votesNo;
        return totalVotes > 0 ? ((votesYes / totalVotes) * 100).toFixed(2) + '%' : '0%';
    }

    function initMap() {
        var mapOptions = {
            center: new google.maps.LatLng(18.2244, -66.0457), // Default center of the map
            zoom: 12 // Default zoom level
        };
        var map = new google.maps.Map(document.getElementById('map'), mapOptions);

        waypoints.forEach(function (item) {
            var markerPosition = new google.maps.LatLng(item.fields.latitude, item.fields.longitude);
            var marker = new google.maps.Marker({
                position: markerPosition,
                map: map,
                title: item.fields.name
            });

            // Add click event to each marker to open the corresponding Bootstrap modal
            marker.addListener('click', function() {
                updateAndShowModal(item);
            });
        });
    }
    </script>

    <!-- Load the Google Maps API script asynchronously with a callback to initMap -->
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC7mz3cFgW2AiTqfBAGQdp7NooU6eq0Ci4&callback=initMap&libraries=places"></script>
    <script src="https://unpkg.com/htmx.org@1.9.11/dist/htmx.min.js"></script>
    <script>
      document.body.addEventListener('htmx:configRequest', (event) => {
        var csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
        event.detail.headers['X-CSRFToken'] = csrfToken;
      });
    </script>

    <!-- Waypoint voting modals -->
    {% for waypoint in waypoints %}
    <div class="modal fade" id="waypointModal-{{ waypoint.pk }}" tabindex="-1" role="dialog" aria-labelledby="waypointModalLabel-{{ waypoint.pk }}" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="waypointModalLabel-{{ waypoint.pk }}">{{ waypoint.name }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="voteInfo-{{ waypoint.pk }}">
                    <p>{{ waypoint.description }}</p>
                    <p>Vote Score: <span id="voteScore-{{ waypoint.pk }}">{{ vote_scores|get_by_key:waypoint.pk }}</span></p>
                    <p>Vote Percentage: <span id="votePercentage-{{ waypoint.pk }}">{{ vote_percentages|get_by_key:waypoint.pk }}%</span></p>
                </div>
                <div class="modal-footer">
                    <!-- Simple Bootstrap buttons for voting -->
                    <button type="button" class="btn btn-success" hx-post="{% url 'resource_maps:vote_waypoint' waypoint.pk 'yes' %}" hx-trigger="click" hx-target="#voteInfo-{{ waypoint.pk }}" hx-swap="innerHTML" hx-after-swap="updateModalContent">Yes</button>
                    <button type="button" class="btn btn-danger" hx-post="{% url 'resource_maps:vote_waypoint' waypoint.pk 'no' %}" hx-trigger="click" hx-target="#voteInfo-{{ waypoint.pk }}" hx-swap="innerHTML" hx-after-swap="updateModalContent">No</button>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- New Section for Listing Active Waypoints -->
    <div class="container mt-4">
        <h3>Active Waypoints</h3>
        <div class="list-group">
        {% for waypoint in waypoints %}
            <a href="#" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
              {{ waypoint.name }}
              <span class="badge badge-primary badge-pill">{{ waypoint.vote_score }}</span>
            </a>
            {% endfor %}
        </div>
    </div>
    {% endblock %}

resource_maps/templates/resource_maps/waypoint_info.html
{% load static %}
<strong>Waypoint Information</strong>

{% block content %}
<div class="container mt-4">
    <h2>{{ waypoint.name }}</h2>
    <p>{{ waypoint.description }}</p>
    <div>
        <strong>Vote Score:</strong> {{ vote_score }}<br>
        <strong>Vote Percentage:</strong> {{ vote_percentage }}%
    </div>
    <!-- Other details and potentially a map showing the location -->
</div>
{% endblock %}